name: CI

on:
  push:
    branches:
      - master

env:
  GIT_USER: mornw
  GIT_EMAIL: 1114128406@qq.com
  DEPLOY_REPO: onlywant/onlywant.github.io
  DEPLOY_BRANCH: main 
  THEME_REPO: Siricee/hexo-theme-Chic
  THEME_BRANCH: master
jobs:
  build:
    name: Build on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: [12.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout theme repo
        uses: actions/checkout@v2
        with:
          repository: ${{ env.THEME_REPO }}
          ref: ${{ env.THEME_BRANCH }}
          path: themes/chic

      - name: Checkout deploy repo
        uses: actions/checkout@v2
        with:
          repository: ${{ env.DEPLOY_REPO }}
          ref: ${{ env.DEPLOY_BRANCH }}
          path: .deploy_git

      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}

      - name: Configuration environment
        env:
          HEXO_DEPLOY_PRI: ${{secrets.HEXO_DEPLOY_PRI}}
        run: |
          sudo timedatectl set-timezone "Asia/Shanghai"
          mkdir -p ~/.ssh/
          echo "$HEXO_DEPLOY_PRI" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.name $GIT_USER
          git config --global user.email $GIT_EMAIL
          cp _config.chic.yml themes/chic/_config.yml
          cp title.ico themes/chic/source/title.ico
          cp avatar.jpg themes/chic/source/image/avatar.jpg
          cp font.styl themes/chic/source/css/font.styl

      - name: Install dependencies
        run: |
          npm install

      - name: Deploy hexo
        run: |
          npm run clean
          npm run build
          npm run deploy
